# Generated by Django 6.0.5 on 2026-05-18 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='약 이름')),
                ('intake_time', models.CharField(help_text='예: 08:00,12:00,18:00', max_length=255, verbose_name='복용 시간')),
                ('frequency', models.CharField(max_length=100, verbose_name='복용 횟수')),
                ('is_active', models.BooleanField(default=True, verbose_name='복용 중')),
                ('alarm_enabled', models.BooleanField(default=True, verbose_name='알림 사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '복용 약',
                'verbose_name_plural': '복용 약',
                'ordering': ['-created_at'],
            },
        ),
    ]
