# Generated by Django 6.0.5 on 2026-05-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedicine',
            name='appearance',
            field=models.CharField(blank=True, max_length=200, verbose_name='성상'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='색깔'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='image',
            field=models.CharField(default='medicines/img/tylenol.jpg', help_text='static 기준 경로', max_length=255, verbose_name='약 이미지'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='ingredient_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='성분명'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True, verbose_name='제조일자'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='제조사'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='mark_back',
            field=models.CharField(blank=True, max_length=100, verbose_name='식별표시(뒤)'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='mark_front',
            field=models.CharField(blank=True, max_length=100, verbose_name='식별표시(앞)'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='남은 수량(정)'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='총 수량(정)'),
        ),
    ]
