# Generated by Django 6.0.5 on 2026-05-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_usermedicine_appearance_usermedicine_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedicine',
            name='dose_per_day',
            field=models.PositiveIntegerField(default=1, verbose_name='하루 복용 횟수'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='복용 일수'),
        ),
        migrations.AddField(
            model_name='usermedicine',
            name='meal_timing',
            field=models.CharField(choices=[('before', '식사 전'), ('after', '식사 후')], default='after', max_length=20, verbose_name='식전/식후'),
        ),
    ]
